### ISSUE TITLE
Kayak doesn't start after installation

### ISSUE THREAD

**Issue by Morsmalleo** [ParrotSec/car-hacking-tools#1]
After git cloning the 'car hacking tools', and running sudo make install, Kayak does not want to work at all. Can someone help me with this please I have installed it on Kali Linux 2020.4 for Virtualbox

**Comment by Morsmalleo** [comment]
problem solved. Creating a fork with this information on the README.md 

**HOW TO INSTALL KAYAK**

**INSTALLING REQUIREMENTS**
`sudo apt install build-essential automake dh-autoreconf libusb-1.0-0-dev libconfig-dev cmake g++ gcc maven`

**INSTALLING KAYAK & SOCKETCAND**
git clone the following repositories
- https://github.com/linux-can/socketcand
- https://github.com/dschanoeh/Kayak

**Now move the socketcand folder into the Kayak folder as shown below, then cd into the socketcand folder and do the following**
`sudo mv socketcand /home/kali/Kayak/`
`cd /home/kali/Kayak/socketcand`
`sudo ./autogen.sh`
`sudo ./configure`
`sudo make`
`sudo make install -y`

**Comment by PalinuroSec** [comment]
hello. from what i know the kayak project was discontinued and is no longer maintained, and our decision was to remove it from the project

**Comment by Morsmalleo** [comment]
> hello. from what i know the kayak project was discontinued and is no longer maintained, and our decision was to remove it from the project

oh Ok, that's a shame, I loved Kayak, great to always get a reply from you though @PalinuroSec :)
